
# Autogenerated file
MODULE_VERSION = "0.0.0-dev"
GIT_COMMIT_HASH = "d2d91e0e46458750f2d583a2faf9d0c1c457fa7a"
GIT_REMOTE_URL = "ssh://git@stash.corp.alleninstitute.org:7999/aicsad/aics-segmentation.git"
