
# Autogenerated file
MODULE_VERSION = "0.0"
GIT_COMMIT_HASH = "f2600ce2af70f03ea3befea356637c1db3cd219b"
GIT_REMOTE_URL = "http://jianxuc@stash.corp.alleninstitute.org/scm/aicsad/aics-segmentation.git"
